# Supported intents (upper snake for API consistency)
INTENT_WFH_REQUEST = "WFH_REQUEST"
INTENT_ATTENDANCE_CORRECTION = "ATTENDANCE_CORRECTION"
INTENT_REQUEST_STATUS = "REQUEST_STATUS"
INTENT_HR_POLICY = "HR_POLICY"
INTENT_APPROVAL_ESCALATION = "APPROVAL_ESCALATION"
INTENT_UNKNOWN = "UNKNOWN"

ALL_INTENTS = frozenset(
    {
        INTENT_WFH_REQUEST,
        INTENT_ATTENDANCE_CORRECTION,
        INTENT_REQUEST_STATUS,
        INTENT_HR_POLICY,
        INTENT_APPROVAL_ESCALATION,
        INTENT_UNKNOWN,
    }
)
